### ISSUE TITLE
Block height is not showing

### ISSUE THREAD

**Issue by AmardeepSambaru** [DefiLlama/chainlist#1155]
Hi Team,

Good evening.

We have added two public endpoints to the Chain list and raised a PR, which has been merged by your team. The two endpoints are now available in the UI, but it is not displaying the block height.

Although it initially seemed that our endpoints were not working, we have confirmed that they are functioning correctly and showing the block height when using the curl command.

Please see the details of the protocols and endpoints below:

**Etherlink testnet:**
      **chain id:** 128123
      **public endpoint:** https://etherlink-ghostnet-6lcp5r.zeeve.net/rpc

**Bahamut:**
         **chain id:** 5165
            **public endpoint:** https://Bahamut-mainnet-2h93.zeeve.net

Could you Please look into this issue.

Thanks.
![bahamut](https://github.com/DefiLlama/chainlist/assets/93637202/49b71e5f-3e12-4ed4-9ddb-f154d5f6071d)
![etherlink](https://github.com/DefiLlama/chainlist/assets/93637202/698b8099-4507-417b-83ae-f56da7dfd8cc)

**Comment by 0xngmi** [comment]
if its not showing its because the RPC request to your URL failed

**Comment by 0xngmi** [comment]
to find the issue just open the network tab in your browser's dev console and look into the requests made to your RPCs

**Comment by AmardeepSambaru** [comment]
No, the rpc request is not failed it is working fine.
see the below attached pick and you can also try to execute the curl command

![image](https://github.com/DefiLlama/chainlist/assets/93637202/234c52ab-ecda-4ab6-85d4-6a39a46bb704)

**Comment by 0xngmi** [comment]
Your RPC query is failing when queried from our frontend because it doesn't contain CORS headers

**Comment by Amarylla923** [comment]
None
None
No milestones etc. 
Contrary to code.
Although idk code, I have many milestones 
Tons of work. The API is amarylladavis1@gmail.com 
Many alt pins especially meme coins, as well as the entire mega byte system by utx unit bit coin etc. 
Please do not run my merkle root to the alternate unverse, 
As I stated several times I do not know code, I don't want my funds my coins or anything just dropping into oblivion or a wallet I know not nor who has such as the ever perpetrators Amaryllis pay solutions or Amar Kumar and Moyhnihan from B.of A, keeping in mind US bank and Peoples Choice. 
All the more. Run end point to Amarylladavis1@gmail.com

**Comment by Amarylla923** [comment]
Instead of air dripping my money to random strangers which I am against. 
{[Amarylla jußt recieved notice of my funds being donated or raffled or stolen or misplaced by others. And I Amarylla Davis do insist that immediately stop. Notice given here.}]{[I Amarylla Davis owner of multiple coins and wallets Ethereum, polka dot, or dot, until granted notice given by myself, hal Finney, is a fictional character the wallet is mine or a close relatives of mine, Andy's N'Chain, my 2 children, Cardona(?) Solano(?) either of those I not sure which, Jedi, 100%, Jedi ninja, scaling guacamole, Wile E, Mars, Name, Meme, Schezchuan,(?), Samurai (?) Rafa, all my decadence, Goes, Luigi, Dingo, Hildalgo, Beluga, Sakuro, Ahab, Amp, Ape, ADA, GM , GmZ, Gmt, MJD. mGD, Jed, Amar, Leiftree, ALA, Aurora, Gage cash, Z cash, GHZ, M, ABBA, Glama, Glama, Glaamma, jglaamma, jglaamanaj, Satoshi, Satoshi Nakamota(?), Satoshi Sakamoto, Satoshi Yakaota(?), 1 or 2 1 for sure. Doge, }] I also blocked up tbe mega meta byte bit block system originally before any wallets ever stared collecting the bit units and blocking it to a mega byte block.1998-1999}]

**Comment by AmardeepSambaru** [comment]
@0xngmi 

Thank you so much.
Now it is working

**Comment by AmardeepSambaru** [comment]
@0xngmi

Thank you so much.
Now it is working

**Comment by Amarylla923** [comment]
I don't know what any of this is about, could someone please inform me in
layman terms. Is this Run, and the RPc endpoint of an API other than
anything I have control of. Does this stuff have anything to do with the
currency, the funds, the alt coins that are in wallets I own or that i
created  Or wallets I cannot access. Even wallets that I gave to loved
ones? I apologize because I simply do not understand. Sometimes I gain
entry to my w
Wallets and I am hoping that I didn't set anything up so that my money can
be used. I
Appreciate the help, I enjoy the alt industry, I love naming alt pins and
seeing the idea become popular, a simplle name and concept coming to life.
I also have hard time finding the Jedi coin, did I originally name Jedi
ninja, delete the ninja, and now Jedi simply is not popular or something
like that? How about Jedi Knight than? I have lots others also. No
intellect and as always require assistance. Thank you AmarK923
